language: java
dist: xenial
sudo: false
install: false


jdk:
  - openjdk11

# whitelist
branches:
  only:
    - master
    - /xchart-\d+\.\d+\.\d+-ao/

jobs:
    include:
    - stage: clean package
      skip_cleanup: true
      script: echo "clean and install ..."
      script: "mvn clean package"
      deploy:
            provider: releases
            api_key: $GITHUB_OAUTH_TOKEN
            file: $FILE_TO_DEPLOY
            on:
                tags: true
