language: java
sudo: false

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
install: false
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean test --settings target/travis/settings.xml;
else 
    mvn clean verify --settings target/travis/settings.xml;
fi"

dist: bionic

jdk:
  - openjdk11

# whitelist
branches:
  only:
    - master
    - /xchart-\d+\.\d+\.\d+-ao/

jobs:
    include:
    - stage: clean compile test and release
      skip_cleanup: true
      script: echo "clean and install ..."
      script: "mvn clean install"
      script: echo "Deploying to GitHub releases ..."
      deploy:
            provider: releases
            api_key: $GITHUB_OAUTH_TOKEN
            file: $FILE_TO_DEPLOY
            on:
                tags: true
