language: java
sudo: false

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
install: true
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then 
    mvn clean test --settings target/travis/settings.xml;
else 
    mvn clean verify --settings target/travis/settings.xml;
fi"

dist: trusty

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - /xchart-\d+\.\d+\.\d+-ao/

jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
