language: java
dist: xenial
sudo: false
install: false
script: "mvn clean package"


jdk:
  - openjdk11

# whitelist
branches:
  only:
    - master
    - /xchart-\d+\.\d+\.\d+-ao/

jobs:
    include:
    - stage: clean compile test and install
      skip_cleanup: true
      script: echo "clean and install ..."
      script: "mvn clean install"
    - stage: clean compile test and release
      script: echo "Deploying to GitHub releases ..."
      deploy:
            provider: releases
            api_key: $GITHUB_OAUTH_TOKEN
            file: $FILE_TO_DEPLOY
            on:
                tags: true
